name: Sir FlipReset Watcher âš”ï¸

on:
  schedule:
  workflow_dispatch:        # bouton "Run workflow"

jobs:
  mmr:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: âš”ï¸ Run Sir FlipReset
        run: node mmr-watcher.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
